name: CI
on:
  push:
    branches: 
      - develop
      - stage
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev  # Specify the environment here
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Building the application - artifact" > echo.txt
          cat echo.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: echo.txt
          path: echo.txt

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/heads/develop')  # Only run if the branch is 'main'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: echo.txt
      - name: Deploy
        run: |
          echo "Deploying to dev"
          cat echo.txt
 
  deploy-stage:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/heads/main')  # Only run if the branch is 'main'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: echo.txt

      - name: Use Artifacts
        run: |
          cat output.txt
      - name: Deploy
        run: |
          echo "Deploying to stage"
          cat echo.txt
  
  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags')  # Only run if the tag'
    steps:
      - name: Deploy
        run: |
          echo "Deploying to prod"
          cat echo.txt

