name: CI
on:
  push:
    branches: 
      - develop
      - stage
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: create env file
        run: |
          echo ${{ vars.ENVDEV }}
          echo ${{ vars.ENVDEV }} > env.dev
          cat env.dev
          ls
          pwd
      - name: Build
        run: |
          echo "Building the application - artifact" > echo.txt
          cat echo.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: env.dev
          path: env.dev

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/heads/develop')  # Only run if the branch is 'main'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: env.dev
      - name: Deploy
        run: |
          echo "Deploying to dev"
          ls
          pwd
          cat env.dev
 
  deploy-stage:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/heads/main')  # Only run if the branch is 'main'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: env.dev

      - name: Deploy
        run: |
          echo "Deploying to stage"
          cat env.dev
  
  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags')  # Only run if the tag'
    steps:
      - name: Deploy
        run: |
          echo "Deploying to prod"
          cat echo.txt

