name: CI
on:
  push:
    branches: 
      - develop
      - stage
      - main
    tags:
      - 'v*.*.*'
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: 'us-east-1'
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/develop')
    steps:
      - name: create env file
        run: |
          echo ${{ vars.ENVDEV }} > env.dev
          echo "saved env file ************************"
          source env.dev
          printenv
          echo 'print secrets'
          echo $AWS_ACCESS_KEY_ID
          echo $AWS_SECRET_ACCESS_KEY
          echo $AWS_REGION
      - name: Deploy
        run: |
          echo "Deploying to dev ******************************"
#  deploy-dev:
#    runs-on: ubuntu-latest
#    needs: build
#    if: startsWith(github.ref, 'refs/heads/develop')  # Only run if the branch is 'main'
#    steps:
#      - name: Download Artifacts
#        uses: actions/download-artifact@v3
#        with:
#          name: env.dev
#      - name: Deploy
#        run: |
#          echo "Deploying to dev"
#          ls
#          pwd
#          cat env.dev
# 
#  deploy-stage:
#    runs-on: ubuntu-latest
#    needs: build
#    if: startsWith(github.ref, 'refs/heads/main')  # Only run if the branch is 'main'
#    steps:
#      - name: Download Artifacts
#        uses: actions/download-artifact@v3
#        with:
#          name: env.dev
#
#      - name: Deploy
#        run: |
#          echo "Deploying to stage"
#          cat env.dev
#  
#  deploy-prod:
#    runs-on: ubuntu-latest
#    needs: build
#    if: startsWith(github.ref, 'refs/tags')  # Only run if the tag'
#    steps:
#      - name: Deploy
#        run: |
#          echo "Deploying to prod"
#          cat echo.txt

