name: CI
on:
  push:
    branches: 
      - develop
      - stage
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev  # Specify the environment here
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Building the application..." > echo.txt
          cat echo.txt
  
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/heads/develop')  # Only run if the branch is 'main'
    steps:
      - name: Deploy
        run: |
          echo "Deploying to dev"
          cat echo.txt
 
  deploy-stage:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/heads/main')  # Only run if the branch is 'main'
    steps:
      - name: Deploy
        run: |
          echo "Deploying to stage"
          cat echo.txt

