name: Main Workflow

on:
  push:
    branches:
      - main
      - develop

jobs:
  call-template:
    uses: ./.github/workflows/test-template.yml  # Call the template workflow
    with:
      branch: $GITHUB_REF_NAME
      run_tests: 'false'
      ENVFILE: ${{ github.ref == 'refs/heads/develop' && 'ENVDEV' || 'ENVSTAGE' }}
