name: CI Template

on:
  workflow_call:  # This makes the workflow reusable
    inputs:
      ENVFILE:
        type: string
        required: true
      branch:
        type: string
        description: 'Branch to run the workflow on'
        required: true
        default: 'develop'
      run_tests:
        description: 'Run tests flag'
        required: true
        type: string
        default: 'true'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: set var
        run: |
          cat $ENVFILE || echo wrong cat
          echo $ENVFILE || echo wrong echo
          echo $GITHUB_REF_NAME

      - name: Run tests
        if: ${{ inputs.run_tests == 'true' }}
        run: echo Tests
