name: CI Template

on:
  workflow_call:  # This makes the workflow reusable
    inputs:
      branch:
        type: string
        description: 'Branch to run the workflow on'
        required: true
        default: 'develop'
      run_tests:
        description: 'Run tests flag'
        required: true
        type: string
        default: 'true'

jobs:
  init:
    runs-on: ubuntu-latest
    
    steps:
      - name: Save state
        if: github.ref == 'refs/heads/develop'
        run: echo "env_file=ENVDEV" >> $GITHUB_STATE

      - name: Set output
        run: echo "env_file=ENVDEV" >> $GITHUB_OUTPUT


      - name: Run tests
        if: ${{ inputs.run_tests == 'true' }}
        run: echo Tests
  
  print:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Print
        run: echo $GITHUB_REF_NAME
       
