name: CI Template

on:
  workflow_call:  # This makes the workflow reusable
    inputs:
      ENVFILE:
        type: string
        required: true
      branch:
        type: string
        description: 'Branch to run the workflow on'
        required: true
        default: 'develop'
      run_tests:
        description: 'Run tests flag'
        required: true
        type: string
        default: 'true'

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      env_file: ${{ steps.setvars.outputs.env_file }}
    
    steps:
      - name: Set variables
        id: setvars
        run: |
          if [[ "${{github.base_ref}}" == "develop" ]]; then
            echo "::set-output name=env_file::ENVDEV"
          fi

      - name: Run tests
        if: ${{ inputs.run_tests == 'true' }}
        run: echo Tests
  
  print:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Print
        run: echo "env_file=${{needs.init.outputs.env_file}}"
       
